name: fq-segmentation
channels:
  - pypi
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - pip:
      - segwrap==0.3.3
      - cellpose == 0.6.5
      - matplotlib == 3.4.2
      - scikit-image == 0.19.2

