name: bigfishlive
channels:
  - conda-forge
  - pypi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - ca-certificates=2024.2.2
  - cffi=1.16.0
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - idna=3.4
  - importlib-metadata=7.0.1
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.2.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=13.2.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - openssl=3.2.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - python=3.10
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pyzmq=23.2.0
  - readline=8.2
  - referencing=0.30.2
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1
  - pip:
      - about-time==4.2.1
      - alabaster==0.7.16
      - alive-progress
      - annotated-types==0.6.0
      - app-model==0.2.4
      - appdirs==1.4.4
      - asciitree==0.3.3
      - babel==2.14.0
      - big-fish==0.6.2
      - build==1.0.3
      - cachey==0.2.1
      - cellpose==2.2.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - dask
      - docstring-parser==0.15
      - docutils==0.20.1
      - fasteners==0.19
      - fastremap==1.14.1
      - filelock==3.9.0
      - fonttools==4.47.2
      - freetype-py==2.4.0
      - fsspec==2024.2.0
      - grapheme==0.6.0
      - h5py==3.10.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - imagecodecs==2024.1.1
      - imageio==2.33.1
      - imagesize==1.4.1
      - imaris-ims-file-reader==0.1.8
      - importlib-resources==6.1.1
      - in-n-out==0.1.9
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - kneed
      - lazy-loader==0.3
      - llvmlite==0.42.0
      - locket==1.0.0
      - looseversion==1.3.0
      - magicgui==0.8.1
      - markdown-it-py==3.0.0
      - matplotlib
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mrc==0.3.1
      - mypy-extensions==1.0.0
      - napari==0.4.19
      - napari-bleach-correct==0.0.1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.0a2
      - napari-svg==0.1.10
      - natsort==8.4.0
      - networkx==3.2.1
      - npe2==0.7.4
      - numba==0.59.0
      - numcodecs==0.12.1
      - numpy==1.23.0
      - numpydoc==1.6.0
      - opencv-python-headless==4.9.0.80
      - packaging==23.2
      - pandas==2.2.0
      - partd==1.4.1
      - pillow==10.2.0
      - pint==0.23
      - pooch==1.8.0
      - psygnal==0.9.5
      - pyconify==0.1.6
      - pydantic==2.6.1
      - pydantic-compat==0.1.2
      - pydantic-core==2.16.2
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtgraph==0.13.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - requests==2.31.0
      - rich==13.7.0
      - roifile==2024.1.10
      - scikit-image==0.22.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - session-info==1.0.0
      - snowballstemmer==2.2.0
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stdlib-list==0.10.0
      - superqt==0.6.1
      - sympy==1.12
      - tabulate==0.9.0
      - threadpoolctl==3.2.0
      - tifffile==2024.1.30
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.1
      - torch==2.2.0+cpu
      - tqdm==4.66.2
      - trackpy==0.6.1
      - triangle==20230923
      - typer==0.9.0
      - tzdata==2023.4
      - urllib3==2.2.0
      - vispy==0.14.1
      - wrapt==1.16.0
      - xlsxwriter==3.2.0
      - zarr==2.17.0
