name: segmentation_env
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python=3.10
  - conda-forge::tensorflow
  - coin-or-cbc
  - gurobi
  - jupyter
  - pip
  - pytorch
  - zarr
  - pip:
    - pyqt5
    - napari
    - jupyter nbconvert
    - stardist
    - csbdeep
    - opencv
    - alive_progress
    - gurobi 
    - ultrack 
    - cellpose 
